### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/json/JsonStructure

### ISSUE THREAD

**Issue by yegor256** [randoop/randoop#1066]
I downloaded the archive, unzipped it and then run like this:

```
$ java -cp ~/Downloads/randoop-4.3.1/randoop-all-4.3.1.jar:target/classes randoop.main.Main gentests --test-package com.yegor256.foo
Randoop for Java version 4.3.1.

Throwable thrown while handling command: java.lang.NoClassDefFoundError: javax/json/JsonStructure
java.lang.NoClassDefFoundError: javax/json/JsonStructure
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at randoop.main.GenInputsAbstract.getClassesWithPackageFromDirectory(GenInputsAbstract.java:1203)
	at randoop.main.GenInputsAbstract.getClassnamesFromPackage(GenInputsAbstract.java:1174)
	at randoop.main.GenInputsAbstract.getClassnamesFromArgs(GenInputsAbstract.java:1045)
	at randoop.main.GenTests.handle(GenTests.java:251)
	at randoop.main.Main.nonStaticMain(Main.java:71)
	at randoop.main.Main.main(Main.java:31)
Caused by: java.lang.ClassNotFoundException: javax.json.JsonStructure
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 8 more
```

My `.class` files are in the `target/classes` path.

**Comment by mernst** [comment]
I'm sorry you are having trouble.
Unfortunately, your bug report does not enable us to reproduce the error.

Could you please follow the instructions that were in the issue template?

> The complete commands you ran, so that we can paste them into a command terminal.  Please don't omit any steps, including installing software or setting environment variables.

If you can do this, we will investigate and fix your problem.

One possibility is that not *all* the `.class` files are in `target/classes`.  Where is the `javax.json.JsonStructure` class?  That should be on your classpath.

**Comment by mernst** [comment]
@yegor256 A ping on this issue.

**Comment by yegor256** [comment]
@mernst let me check again. However, I still struggle with finding instructions about how to run Randoop on a Java project (I use Maven layout). Can you please refer me to the right place?

**Comment by mernst** [comment]
I'm closing this issue for now.  We can re-open it if the requested information becomes available.
