### ISSUE TITLE
Randoop fails with a runtime exception when generating tests for spring

### ISSUE THREAD

**Issue by jensdietrich** [randoop/randoop#1100]
In my setup I try to generate tests for spring beans using the following parameters: 

```
--testjar <some-path>/spring-beans-5.3.22.jar --no-regression-assertions --junit-package-name=generated.org.springframework.beans --junit-output-dir=generated-tests --log=randoop-spring-beans-5.3.22.log
```

The classpath work, and I have generated tests for some particular classes successfully. However, when I try to run this on the jar, randoop fails with an IllegalStateException  caused by a failed spring assertion. 

```
Throwable thrown while handling command: java.lang.IllegalStateException: Singleton instance not initialized yet
java.lang.IllegalStateException: Singleton instance not initialized yet
	at org.springframework.util.Assert.state(Assert.java:76)
	at org.springframework.beans.factory.config.AbstractFactoryBean.getSingletonInstance(AbstractFactoryBean.java:188)
	at org.springframework.beans.factory.config.AbstractFactoryBean.access$200(AbstractFactoryBean.java:63)
	at org.springframework.beans.factory.config.AbstractFactoryBean$EarlySingletonInvocationHandler.invoke(AbstractFactoryBean.java:275)
	at com.sun.proxy.$Proxy18.entrySet(Unknown Source)
	at randoop.org.plumelib.util.StringsPlume.mapToStringAndClass(StringsPlume.java:1144)
	at randoop.org.plumelib.util.StringsPlume.toStringAndClass(StringsPlume.java:1027)
	at randoop.org.plumelib.util.StringsPlume.toStringAndClass(StringsPlume.java:1001)
	at randoop.operation.MethodCall.execute(MethodCall.java:170)
	at randoop.operation.TypedOperation.execute(TypedOperation.java:310)
	at randoop.sequence.Statement.execute(Statement.java:163)
	at randoop.sequence.ExecutableSequence.executeStatement(ExecutableSequence.java:415)
	at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:307)
	at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:236)
	at randoop.generation.ForwardGenerator.step(ForwardGenerator.java:237)
	at randoop.generation.AbstractGenerator.createAndClassifySequences(AbstractGenerator.java:321)
	at randoop.main.GenTests.handle(GenTests.java:510)
	at randoop.main.Main.nonStaticMain(Main.java:71)
	at randoop.main.Main.main(Main.java:31)
```

**Comment by jensdietrich** [comment]
I have also notices this exception that always seemed to happen just before:

```
Will try to generate tests for 286 classes.
Removing org.springframework.beans.factory.groovy.GroovyDynamicElementReader$_invokeMethod_closure1 from the classes under test due to problem extracting operations:
java.lang.NullPointerException
	at randoop.reflection.DefaultReflectionPredicate.doNotUseSpecialCase(DefaultReflectionPredicate.java:234)
	at randoop.reflection.DefaultReflectionPredicate.test(DefaultReflectionPredicate.java:106)
	at randoop.reflection.OperationExtractor.visit(OperationExtractor.java:435)
	at randoop.reflection.ReflectionManager.applyTo(ReflectionManager.java:309)
	at randoop.reflection.ReflectionManager.apply(ReflectionManager.java:150)
	at randoop.reflection.OperationExtractor.operations(OperationExtractor.java:216)
	at randoop.reflection.OperationModel.addOperationsFromClasses(OperationModel.java:682)
	at randoop.reflection.OperationModel.createModel(OperationModel.java:173)
	at randoop.main.GenTests.handle(GenTests.java:313)
	at randoop.main.Main.nonStaticMain(Main.java:71)
	at randoop.main.Main.main(Main.java:31)
```
