### ISSUE TITLE
Uncaught exception in thread 'null'

### ISSUE THREAD

**Issue by mdimjasevic** [randoop/randoop#133]
With Randoop 3.0.8 I get an uncaught exception that terminates Randoop on the `summa` benchmark from [SF110](http://www.evosuite.org/experimental-data/sf110/):

```
Explorer = randoop.generation.ForwardGenerator@23e84203

Progress update: test inputs generated=0, failing inputs=0      (Thu Dec 15 03:33:06 CET 2016)Record is 'null'
Uncaught exception in thread 'null'. Processing is unstable and as a result, the JVM will be terminated in 5 seconds
dk.statsbiblioteket.summa.common.filter.object.PayloadException: responsemerger.post
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at randoop.util.ConstructorReflectionCode.runReflectionCodeRaw(ConstructorReflectionCode.java:45)
        at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:49)
        at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:53)
        at randoop.util.RunnerThread.run(RunnerThread.java:46)
```

I started it with a 10-second time limit, ignoring flaky tests, with forbid-null=false, small-tests=true, testsperfile=1, randomseed=10, and a text file listing classes in the project given with the `--classlist` option.

If you need it, I can reconstruct the full invocation command.

**Comment by bjkeller** [comment]
Yes, if you can give more information, that will help.

**Comment by mdimjasevic** [comment]
Hi @bjkeller. Here is the command:

```
java -ea -cp /mnt/storage/sf110/44_summa/bin/lib/jackson-core-asl-1.9.2.jar:/mnt/storage/sf110/44_summa/bin/lib/lucene-analyzers-common-4.0.0.jar:/mnt/storage/sf110/44_summa/bin/lib/logback-classic-1.0.3.jar:/mnt/storage/sf110/44_summa/bin/lib/xz-1.1.jar:/mnt/storage/sf110/44_summa/bin/lib/jackson-xc-1.9.2.jar:/mnt/storage/sf110/44_summa/bin/lib/logback-core-1.0.3.jar:/mnt/storage/sf110/44_summa/bin/lib/lucene-queries-4.0.0.jar:/mnt/storage/sf110/44_summa/bin/lib/ezmorph-1.0.6.jar:/mnt/storage/sf110/44_summa/bin/lib/axis-wsdl4j-1.5.1.jar:/mnt/storage/sf110/44_summa/bin/lib/jetty-util-8.1.2.v20120308.jar:/mnt/storage/sf110/44_summa/bin/lib/solr-analysis-extras-4.0.0.jar:/mnt/storage/sf110/44_summa/bin/lib/h2-1.2.139.jar:/mnt/storage/sf110/44_summa/bin/lib/asm-3.1.jar:/mnt/storage/sf110/44_summa/bin/lib/truezip-driver-tar-7.6.6.jar:/mnt/storage/sf110/44_summa/bin/lib/jersey-json-1.17.1.jar:/mnt/storage/sf110/44_summa/bin/lib/jetty-util-6.1.12.jar:/mnt/storage/sf110/44_summa/bin/lib/WhitespaceTokenizer-2.3.1.jar:/mnt/storage/sf110/44_summa/bin/lib/servlet-api-2.5.jar:/mnt/storage/sf110/44_summa/bin/lib/wstx-asl-3.2.7.jar:/mnt/storage/sf110/44_summa/bin/lib/Tagger-2.3.1.jar:/mnt/storage/sf110/44_summa/bin/lib/jetty-security-8.1.2.v20120308.jar:/mnt/storage/sf110/44_summa/bin/lib/lucene-analyzers-icu-4.0.0.jar:/mnt/storage/sf110/44_summa/bin/lib/commons-codec-1.2.jar:/mnt/storage/sf110/44_summa/bin/lib/jcl-over-slf4j-1.6.4.jar:/mnt/storage/sf110/44_summa/bin/lib/log4j-1.2.14.jar:/mnt/storage/sf110/44_summa/bin/lib/lucene-analyzers-smartcn-4.0.0.jar:/mnt/storage/sf110/44_summa/bin/lib/slf4j-log4j12-1.6.4.jar:/mnt/storage/sf110/44_summa/bin/lib/truezip-file-7.6.6.jar:/mnt/storage/sf110/44_summa/bin/lib/jersey-servlet-1.17.1.jar:/mnt/storage/sf110/44_summa/bin/lib/jetty-webapp-8.1.2.v20120308.jar:/mnt/storage/sf110/44_summa/bin/lib/solr-test-framework-4.0.0.jar:/mnt/storage/sf110/44_summa/bin/lib/solr-solrj-4.0.0.jar:/mnt/storage/sf110/44_summa/bin/lib/json-lib-2.4-jdk15.jar:/mnt/storage/sf110/44_summa/bin/lib/commons-io-2.1.jar:/mnt/storage/sf110/44_summa/bin/lib/commons-lang-2.6.jar:/mnt/storage/sf110/44_summa/bin/lib/lucene-misc-4.0.0.jar:/mnt/storage/sf110/44_summa/bin/lib/solr-core-4.0.0-sources.jar:/mnt/storage/sf110/44_summa/bin/lib/truezip-driver-zip-7.6.6.jar:/mnt/storage/sf110/44_summa/bin/lib/hamcrest-core-1.1.jar:/mnt/storage/sf110/44_summa/bin/lib/commons-lang-2.5.jar:/mnt/storage/sf110/44_summa/bin/lib/jetty-http-8.1.2.v20120308.jar:/mnt/storage/sf110/44_summa/bin/lib/axis-jaxrpc-1.4.jar:/mnt/storage/sf110/44_summa/bin/lib/marc4j-2.4.jar:/mnt/storage/sf110/44_summa/bin/lib/commons-beanutils-1.8.0.jar:/mnt/storage/sf110/44_summa/bin/lib/httpcore-4.2.1.jar:/mnt/storage/sf110/44_summa/bin/lib/jersey-server-1.17.1.jar:/mnt/storage/sf110/44_summa/bin/lib/lucene-queryparser-4.0.0.jar:/mnt/storage/sf110/44_summa/bin/lib/jline-0.9.94.jar:/mnt/storage/sf110/44_summa/bin/lib/marc4j-2.4-normalizer.jar:/mnt/storage/sf110/44_summa/bin/lib/stax-api-1.0-2.jar:/mnt/storage/sf110/44_summa/bin/lib/solr-core-4.0.0.jar:/mnt/storage/sf110/44_summa/bin/lib/jersey-client-1.17.1.jar:/mnt/storage/sf110/44_summa/bin/lib/heritrix-1.14.3.jar:/mnt/storage/sf110/44_summa/bin/lib/jackson-jaxrs-1.9.2.jar:/mnt/storage/sf110/44_summa/bin/lib/commons-collections-3.2.1.jar:/mnt/storage/sf110/44_summa/bin/lib/icu4j-4.6.jar:/mnt/storage/sf110/44_summa/bin/lib/lucene-core-4.0.0.jar:/mnt/storage/sf110/44_summa/bin/lib/lucene-grouping-4.0.0.jar:/mnt/storage/sf110/44_summa/bin/lib/jersey-core-1.17.1.jar:/mnt/storage/sf110/44_summa/bin/lib/jetty-6.1.12.jar:/mnt/storage/sf110/44_summa/bin/lib/uimaj-core-2.3.1.jar:/mnt/storage/sf110/44_summa/bin/lib/httpclient-4.2.1.jar:/mnt/storage/sf110/44_summa/bin/lib/jettison-1.1.jar:/mnt/storage/sf110/44_summa/bin/lib/lucene-sandbox-4.0.0.jar:/mnt/storage/sf110/44_summa/bin/lib/jetty-xml-8.1.2.v20120308.jar:/mnt/storage/sf110/44_summa/bin/lib/commons-discovery-0.2.jar:/mnt/storage/sf110/44_summa/bin/lib/lucene-analyzers-stempel-4.0.0.jar:/mnt/storage/sf110/44_summa/bin/lib/lucene-test-framework-4.0.0.jar:/mnt/storage/sf110/44_summa/bin/lib/lucene-analyzers-uima-4.0.0.jar:/mnt/storage/sf110/44_summa/bin/lib/janino-2.5.10.jar:/mnt/storage/sf110/44_summa/bin/lib/javax.servlet-3.0.0.v201112011016.jar:/mnt/storage/sf110/44_summa/bin/lib/jetty-io-8.1.2.v20120308.jar:/mnt/storage/sf110/44_summa/bin/lib/lucene-memory-4.0.0.jar:/mnt/storage/sf110/44_summa/bin/lib/commons-fileupload-1.2.1.jar:/mnt/storage/sf110/44_summa/bin/lib/jaxb-api-2.2.2.jar:/mnt/storage/sf110/44_summa/bin/lib/commons-httpclient-3.1.jar:/mnt/storage/sf110/44_summa/bin/lib/commons-logging-1.1.jar:/mnt/storage/sf110/44_summa/bin/lib/lucene-codecs-4.0.0.jar:/mnt/storage/sf110/44_summa/bin/lib/jackson-mapper-asl-1.9.2.jar:/mnt/storage/sf110/44_summa/bin/lib/fastutil-5.0.4.jar:/mnt/storage/sf110/44_summa/bin/lib/randomizedtesting-runner-2.0.1.jar:/mnt/storage/sf110/44_summa/bin/lib/xstream-1.3.1.jar:/mnt/storage/sf110/44_summa/bin/lib/bcprov-jdk16-1.46.jar:/mnt/storage/sf110/44_summa/bin/lib/jetty-server-8.1.2.v20120308.jar:/mnt/storage/sf110/44_summa/bin/lib/axis-saaj-1.4.jar:/mnt/storage/sf110/44_summa/bin/lib/servlet-api-2.5-6.1.12.jar:/mnt/storage/sf110/44_summa/bin/lib/truezip-driver-file-7.6.6.jar:/mnt/storage/sf110/44_summa/bin/lib/jakarta-regexp-1.4.jar:/mnt/storage/sf110/44_summa/bin/lib/guava-r05.jar:/mnt/storage/sf110/44_summa/bin/lib/commons-codec-1.6.jar:/mnt/storage/sf110/44_summa/bin/lib/commons-compress-1.4.1.jar:/mnt/storage/sf110/44_summa/bin/lib/commons-cli-1.1.jar:/mnt/storage/sf110/44_summa/bin/lib/truezip-swing-7.6.6.jar:/mnt/storage/sf110/44_summa/bin/lib/lucene-suggest-4.0.0.jar:/mnt/storage/sf110/44_summa/bin/lib/jetty-servlet-8.1.2.v20120308.jar:/mnt/storage/sf110/44_summa/bin/lib/jetty-continuation-8.1.2.v20120308.jar:/mnt/storage/sf110/44_summa/bin/lib/slf4j-api-1.6.4.jar:/mnt/storage/sf110/44_summa/bin/lib/tika-core-0.6.jar:/mnt/storage/sf110/44_summa/bin/lib/jaxb-impl-2.2.3-1.jar:/mnt/storage/sf110/44_summa/bin/lib/httpmime-4.1.3.jar:/mnt/storage/sf110/44_summa/bin/lib/commons-codec-1.7.jar:/mnt/storage/sf110/44_summa/bin/lib/sbutil-0.5.12.jar:/mnt/storage/sf110/44_summa/bin/lib/axis-1.4.jar:/mnt/storage/sf110/44_summa/bin/lib/truezip-kernel-7.6.6.jar:/mnt/storage/sf110/44_summa/bin/lib/activation-1.1.jar:/mnt/storage/jdoop/lib/randoop.jar:/mnt/storage/jdoop/lib/junit4.jar:/mnt/storage/jdoop/lib/hamcrest-core-1.3.jar:/mnt/storage/sf110/44_summa/bin randoop.main.Main gentests --classlist=classlist.txt --junit-output-dir=tests-round-1 --regression-test-basename=Regression1Test --timelimit=10 --forbid-null=false --small-tests=true --testsperfile=1 --ignore-flaky-tests --randomseed=10
```

All I get out of this is a file `log/logfile.log`, but I'm not sure if that's produced by Randoop itself or by the benchmark under test.
