### ISSUE TITLE
Randoop crashes: Substitutions not disjoint, and map T to distinct types

### ISSUE THREAD

**Issue by mdimjasevic** [randoop/randoop#142]
With Randoop 3.0.8 I get it crashed by running it on the 57_hft-bomberman benchmark from [SF110](http://www.evosuite.org/experimental-data/sf110/):

```
Throwable thrown while handling command: java.lang.IllegalArgumentException: Substitutions not disjoint, and map T to distinct types
java.lang.IllegalArgumentException: Substitutions not disjoint, and map T to distinct types
        at randoop.types.Substitution.extend(Substitution.java:165)
        at randoop.types.ClassOrInterfaceType.getInstantiatingSubstitution(ClassOrInterfaceType.java:283)
        at randoop.reflection.OperationExtractor.addOperation(OperationExtractor.java:79)
        at randoop.reflection.OperationExtractor.visit(OperationExtractor.java:136)
        at randoop.reflection.ReflectionManager.applyTo(ReflectionManager.java:269)
        at randoop.reflection.ReflectionManager.apply(ReflectionManager.java:117)
        at randoop.reflection.OperationModel.addOperations(OperationModel.java:375)
        at randoop.reflection.OperationModel.createModel(OperationModel.java:140)
        at randoop.main.GenTests.handle(GenTests.java:193)
        at randoop.main.Main.nonStaticMain(Main.java:63)
        at randoop.main.Main.main(Main.java:27)

Randoop failed.
Last sequence under execution: null
```

Here is how I started Randoop:

```
java -ea -cp /mnt/storage/sf110/57_hft-bomberman/bin/lib/cglib-2.1.3.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/hibernate-search.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/lucene-analyzers-2.1.0.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/jl1.0.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/hibernate3.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/asm-attrs.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/freemarker.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/ejb3-persistence.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/hibernate-annotations.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/commons-collections-2.1.1.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/jta.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/hibernate-entitymanager.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/lucene-core-2.1.0.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/c3p0-0.9.1.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/dom4j-1.6.1.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/hibernate-validator.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/ehcache-1.2.3.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/postgresql-8.2-504.jdbc3.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/commons-logging-1.0.4.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/javassist.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/antlr-2.7.6.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/asm.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/log4j.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/log4j-1.2.11.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/hsqldb-1.8.0.7.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/jboss-archive-browsing.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/hibernate-commons-annotations.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/hibernate-tools.jar:/mnt/storage/sf110/57_hft-bomberman/bin/lib/jtidy-r8-20060801.jar:/mnt/storage/sf110/57_hft-bomberman/bin:/mnt/storage/jdoop/lib/junit4.jar:/mnt/storage/jdoop/lib/hamcrest-core-1.3.jar:/mnt/storage/jdoop/lib/randoop.jar randoop.main.Main gentests --classlist=classlist.txt --junit-output-dir=tests-round-5 --regression-test-basename=Regression5Test --timelimit=4 --forbid-null=false --small-tests=true --testsperfile=1 --ignore-flaky-tests --randomseed=15
```

The list of classes used: 
[classlist.txt](https://github.com/randoop/randoop/files/669892/classlist.txt)

**Comment by bjkeller** [comment]
Marko,
Thanks for the report, and especially the details.  It will probably be January before I have a chance to determine what is going on here.
Ben
