### ISSUE TITLE
Capture conversion variable instantiation chosen before bound instantiated

### ISSUE THREAD

**Issue by bjkeller** [randoop/randoop#145]
Exception thrown during execution on apache commons collection 4.4.1.

```
java.lang.IllegalArgumentException: substitution [Capture80 of ? super T := org.apache.commons.collections4.functors.ComparatorPredicate.Criterion] does not instantiate T
	at randoop.types.LazyParameterBound.isLowerBound(LazyParameterBound.java:230)
	at randoop.types.ReferenceType.isInstantiationOf(ReferenceType.java:150)
	at randoop.types.ClassOrInterfaceType.isInstantiationOf(ClassOrInterfaceType.java:339)
	at randoop.types.NonParameterizedType.isInstantiationOf(NonParameterizedType.java:173)
	at randoop.types.ReferenceArgument.isInstantiationOf(ReferenceArgument.java:115)
	at randoop.types.InstantiatedType.isInstantiationOf(InstantiatedType.java:326)
	at randoop.types.EagerReferenceBound.isUpperBound(EagerReferenceBound.java:102)
	at randoop.types.IntersectionTypeBound.isUpperBound(IntersectionTypeBound.java:171)
	at randoop.types.ReferenceType.isInstantiationOf(ReferenceType.java:151)
	at randoop.types.ClassOrInterfaceType.isInstantiationOf(ClassOrInterfaceType.java:339)
	at randoop.types.InstantiatedType.isInstantiationOf(InstantiatedType.java:319)
	at randoop.types.ReferenceArgument.isInstantiationOf(ReferenceArgument.java:115)
	at randoop.types.InstantiatedType.isInstantiationOf(InstantiatedType.java:326)
	at randoop.reflection.TypeInstantiator.selectMatch(TypeInstantiator.java:197)
	at randoop.reflection.TypeInstantiator.instantiateOperationTypes(TypeInstantiator.java:223)
	at randoop.reflection.TypeInstantiator.instantiate(TypeInstantiator.java:83)
	at randoop.generation.ForwardGenerator.createNewUniqueSequence(ForwardGenerator.java:327)
	at randoop.generation.ForwardGenerator.step(ForwardGenerator.java:140)
	at randoop.generation.AbstractGenerator.explore(AbstractGenerator.java:320)
	at randoop.main.GenTests.handle(GenTests.java:379)

Randoop failed.
	at randoop.main.Main.nonStaticMain(Main.java:63)
	at randoop.main.Main.main(Main.java:27)
Last sequence under execution: java.util.ArrayList<java.util.Comparator<org.apache.commons.collections4.ResettableIterator<java.lang.CharSequence>>> arraylist_comparator_resettableiterator_charSequence0 = new java.util.ArrayList<java.util.Comparator<org.apache.commons.collections4.ResettableIterator<java.lang.CharSequence>>>();
org.apache.commons.collections4.comparators.ComparatorChain<org.apache.commons.collections4.ResettableIterator<java.lang.CharSequence>> comparatorchain_resettableiterator_charSequence1 = new org.apache.commons.collections4.comparators.ComparatorChain<org.apache.commons.collections4.ResettableIterator<java.lang.CharSequence>>((java.util.List<java.util.Comparator<org.apache.commons.collections4.ResettableIterator<java.lang.CharSequence>>>)arraylist_comparator_resettableiterator_charSequence0);
java.util.ArrayList<java.util.AbstractCollection<java.util.Comparator<org.apache.commons.collections4.ResettableIterator<java.lang.CharSequence>>>> arraylist_abstractcollection_comparator_resettableiterator_charSequence2 = new java.util.ArrayList<java.util.AbstractCollection<java.util.Comparator<org.apache.commons.collections4.ResettableIterator<java.lang.CharSequence>>>>();
boolean b3 = arraylist_abstractcollection_comparator_resettableiterator_charSequence2.add((java.util.AbstractCollection<java.util.Comparator<org.apache.commons.collections4.ResettableIterator<java.lang.CharSequence>>>)arraylist_comparator_resettableiterator_charSequence0);
boolean b4 = org.apache.commons.collections4.CollectionUtils.isNotEmpty((java.util.Collection<java.util.AbstractCollection<java.util.Comparator<org.apache.commons.collections4.ResettableIterator<java.lang.CharSequence>>>>)arraylist_abstractcollection_comparator_resettableiterator_charSequence2);
arraylist_abstractcollection_comparator_resettableiterator_charSequence2.clear();
org.apache.commons.collections4.Predicate<org.apache.commons.collections4.functors.ComparatorPredicate.Criterion> predicate_criterion6 = org.apache.commons.collections4.PredicateUtils.truePredicate();
java.util.ArrayList<org.apache.commons.collections4.Predicate<org.apache.commons.collections4.functors.ComparatorPredicate.Criterion>> arraylist_predicate_criterion7 = new java.util.ArrayList<org.apache.commons.collections4.Predicate<org.apache.commons.collections4.functors.ComparatorPredicate.Criterion>>();
boolean b8 = arraylist_predicate_criterion7.add(predicate_criterion6);
org.apache.commons.collections4.Predicate<org.apache.commons.collections4.functors.ComparatorPredicate.Criterion> predicate_criterion9 = org.apache.commons.collections4.PredicateUtils.truePredicate();
java.util.ArrayList<org.apache.commons.collections4.Predicate<org.apache.commons.collections4.functors.ComparatorPredicate.Criterion>> arraylist_predicate_criterion10 = new java.util.ArrayList<org.apache.commons.collections4.Predicate<org.apache.commons.collections4.functors.ComparatorPredicate.Criterion>>();
boolean b11 = arraylist_predicate_criterion10.add(predicate_criterion9);
boolean b12 = arraylist_predicate_criterion7.addAll((java.util.Collection<org.apache.commons.collections4.Predicate<org.apache.commons.collections4.functors.ComparatorPredicate.Criterion>>)arraylist_predicate_criterion10);
int i13 = arraylist_abstractcollection_comparator_resettableiterator_charSequence2.lastIndexOf((java.lang.Object)arraylist_predicate_criterion10);
```

Log indicates
```
Selected operation: <T> org.apache.commons.collections4.functors.OnePredicate<T>.onePredicate : (java.util.Collection<? extends org.apache.commons.collections4.Predicate<? super T>>) -> org.apache.commons.collections4.Predicate<T>
```
and
```
Applying capture conversion to <T> org.apache.commons.collections4.functors.OnePredicate<java.util.Collection<java.lang.Comparable<java.lang.String>>>.onePredicate : (java.util.Collection<? extends org.apache.commons.collections4.Predicate<? super T>>) -> org.apache.commons.collections4.Predicate<T>
```

**Comment by bjkeller** [comment]
this appears to be fixed, but need to add test

**Comment by bjkeller** [comment]
fixed by https://github.com/randoop/randoop/commit/6baab237decb87ccedb5b53f77a174e2f656c40b
