### ISSUE TITLE
literals-file=CLASSES string length causes IllegalArgumentException

### ISSUE THREAD

**Issue by JSunde** [randoop/randoop#148]
When Randoop is run with --literals-file=CLASSES on a class with an extremely long string, an IllegalArgumentException is thrown, causing randoop to exit.
`Throwable thrown while handling command: java.lang.IllegalArgumentException: String too long, length = 17628
java.lang.IllegalArgumentException: String too long, length = 17628
	at randoop.operation.NonreceiverTerm.<init>(NonreceiverTerm.java:80)
	at randoop.util.ClassFileConstants.toMap(ClassFileConstants.java:586)
	at randoop.reflection.ClassLiteralExtractor.visitBefore(ClassLiteralExtractor.java:30)
	at randoop.reflection.ReflectionManager.visitBefore(ReflectionManager.java:312)
	at randoop.reflection.ReflectionManager.apply(ReflectionManager.java:109)
	at randoop.reflection.ReflectionManager.apply(ReflectionManager.java:90)
	at randoop.reflection.OperationModel.addClassTypes(OperationModel.java:324)
	at randoop.reflection.OperationModel.createModel(OperationModel.java:132)
	at randoop.main.GenTests.handle(GenTests.java:192)
	at randoop.main.Main.nonStaticMain(Main.java:63)
	at randoop.main.Main.main(Main.java:27)

Randoop failed.`

I understand that there is a max string length, however it would be more robust if a string too large was ignored rather than causing the program to crash.

**Comment by bjkeller** [comment]
This suggestion seems fine, and, in fact, when `--literals-file=CLASSES` it would make sense to just skip anything that cannot be written to a test.

**Comment by mernst** [comment]
I don't think that Randoop should silently ignore input.  It could give a user-friendly warning, though.  I agree a crash is unacceptable.

**Comment by bjkeller** [comment]
Commit https://github.com/randoop/randoop/commit/b1e444a730b8fad04a10c9a61fbd1702b243b5a6
changes behavior, but needs a test!

**Comment by mernst** [comment]
Thanks for the bug report.
Can you please give a concrete test case that reproduces the problem? That will save us time, since you already have a command line and files that produce this result. It will also enable us to test a fix to ensure that it actually works for you.

**Comment by JSunde** [comment]
Here is a simple example with only one file from the JFreeChart project that fails. If you download and extract the contents and then run `java -ea -classpath .:./randoop-all-3.0.8.jar randoop.main.Main gentests --testclass=Licences --literals-file=CLASSES` from within the unzipped directory Randoop will fail with the `java.lang.IllegalArgumentException: STring too long` error.

[StringTooLongEx.zip](https://github.com/randoop/randoop/files/812243/StringTooLongEx.zip)

**Comment by robryb** [comment]
I ran the command line as prescribed above and reproduced the error:

**$ java -ea -classpath .:./randoop-all-3.0.8.jar randoop.main.Main gentests --testclass=Licences --literals-file=CLASSES**
policy = sun.security.provider.PolicyFile@6d03e736

Throwable thrown while handling command: java.lang.IllegalArgumentException: String too long, length = 17628
java.lang.IllegalArgumentException: String too long, length = 17628
	at randoop.operation.NonreceiverTerm.<init>(NonreceiverTerm.java:80)
	at randoop.util.ClassFileConstants.toMap(ClassFileConstants.java:586)
	at randoop.reflection.ClassLiteralExtractor.visitBefore(ClassLiteralExtractor.java:30)
	at randoop.reflection.ReflectionManager.visitBefore(ReflectionManager.java:306)
	at randoop.reflection.ReflectionManager.apply(ReflectionManager.java:103)
	at randoop.reflection.ReflectionManager.apply(ReflectionManager.java:84)
	at randoop.reflection.OperationModel.addClassTypes(OperationModel.java:324)
	at randoop.reflection.OperationModel.createModel(OperationModel.java:132)
	at randoop.main.GenTests.handle(GenTests.java:193)
	at randoop.main.Main.nonStaticMain(Main.java:63)
	at randoop.main.Main.main(Main.java:27)

Randoop failed.
Last sequence under execution: null

---

I then ran Randoop using my local installation. I have Randoop version 4.1.0 installed on a VirtualBox VM and I ran the following command line:

**$ java -ea -classpath .:$RANDOOP_JAR:$RANDOOP_PATH:$JUNIT_JAR:$HAMCREST_JAR:$HAMCREST_PATH randoop.main.Main gentests  --testclass=Licences --literals-file=CLASSES --time-limit=60**

The result was a pair of warning messages:

**Ignoring String constant value: String too long, length = 17628
Ignoring String constant value: String too long, length = 25939**

For the full log, please see:

[Randoop_issue_148.txt](https://github.com/randoop/randoop/files/5521301/Randoop_issue_148.txt)

This result meets the specification that the error should be reported, not ignored. The attached log file indicates that a normal Randoop run occurred after the issue was reported in a user friendly way. I recommend that the bug be closed.

If this test report is insufficient, please let me know what test or report would be sufficient to close the issue ticket.
