### ISSUE TITLE
Randoop terminates prematurely on many SF110 benchmarks

### ISSUE THREAD

**Issue by mdimjasevic** [randoop/randoop#160]
I've reported several issues with running Randoop on the [SF110 benchmarks](http://www.evosuite.org/experimental-data/sf110/) before, but there seem to be more.

For a timelimit of 10 minutes per benchmark for Randoop to generate test cases, Randoop 3.0.9 terminates before the timelimit without outputting any test cases to the file system. These are benchmarks that this issue happens with:

19_jmca
27_gangup
29_apbsmem
36_schemaspy
38_javabullboard
39_diffi
41_follow
56_jhandballmoves
61_noen
80_wheelwebtool
82_ipcalculator
89_jiggler
91_classviewer
99_newzgrabber
100_jgaap
102_squirrel-sql
105_freemind

This is an example of how I start Randoop:

```
Randoop: java $JVM_FLAGS -ea -cp /benchmark/bin/lib/skinlf.jar:/benchmark/bin/lib/jogl.jar:/benchmark/bin/lib/xith3d.jar:/benchmark/bin/lib/joal.jar:/benchmark/bin/lib/xith-md2.jar:/benchmark/bin/lib/vecmath.jar:/benchmark/bin/lib/js.jar:/benchmark/bin/lib/xith-obj.jar:/benchmark/bin:/home/debian/jdoop/lib/junit4.jar:/home/debian/jdoop/lib/hamcrest-core-1.3.jar:/home/debian/jdoop/lib/randoop.jar randoop.main.Main gentests --classlist=classlist.txt --junit-output-dir=tests-round-1 --regression-test-basename=Regression1Test --timelimit=600 --forbid-null=false --small-tests=true --testsperfile=1 --ignore-flaky-tests --randomseed=10
```

This would end in the following exception. For 6 of the problematic benchmarks there would be an additional message that reads "Killed", but I don't know what reports the message.

```
Exception in thread "Thread-543" java.lang.NullPointerException
        at gui.WorldPanel$WorldView.run(WorldPanel.java:198)
        at java.lang.Thread.run(Thread.java:745)
java.io.FileNotFoundException: dat/maps/ist.map (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at java.io.FileReader.<init>(FileReader.java:58)
        at gui.Map.open(Map.java:166)
        at gui.Map.<init>(Map.java:155)
        at gui.WorldPanel$WorldView.<init>(WorldPanel.java:167)
        at gui.WorldPanel.<init>(WorldPanel.java:383)
        at sun.reflect.GeneratedConstructorAccessor5.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at randoop.util.ConstructorReflectionCode.runReflectionCodeRaw(ConstructorReflectionCode.java:45)
        at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:49)
        at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:53)
        at randoop.util.RunnerThread.run(RunnerThread.java:46)
Killed
```

**Comment by mdimjasevic** [comment]
My hunch is that the 3.0.10 isn't addressing any of these issues. The release notes for 3.0.10 read, "Avoids Randoop failures due to issues that arise during test generation, allowing test generation to complete in these cases." However, by running it on SF110 with a 1-hour time limit I have 23/74 that finish/fail in less than an hour with no generated test cases, which confirms an earlier experience with 3.0.9.

**Comment by bjkeller** [comment]
You are correct -- 3.0.10 deals with cases where Randoop has decided something is wrong and throws an exception.  In the cases you've reported, the termination seems to be external.
