### ISSUE TITLE
Throwable thrown while handling command: java.lang.NoClassDefFoundError: Could not initialize class sun.security.jca.Providers

### ISSUE THREAD

**Issue by markro49** [randoop/randoop#371]
1) set up the randoop pascali coverage suite => https://gitlab.cs.washington.edu/randoop/pascali-coverage
2) cd to the directory established in step (1)
3) cd integration-test2
4) run './run_randoop.py jcodec'
5) the various output files will be in integration-test2/corpus/jcodec/dljc-out
6) i have attached randoop.log from that directory
[randoop.log](https://github.com/randoop/randoop/files/2027505/randoop.log)

**Comment by mernst** [comment]
Here is the stack trace from your log:

```
Throwable thrown while handling command: java.lang.NoClassDefFoundError: Could not initialize class sun.security.jca.Providers
java.lang.NoClassDefFoundError: Could not initialize class sun.security.jca.Providers
	at java.security.SecureRandom.getPrngAlgorithm(SecureRandom.java:558)
	at java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:194)
	at java.security.SecureRandom.<init>(SecureRandom.java:162)
	at java.nio.file.TempFileHelper.<clinit>(TempFileHelper.java:56)
	at java.nio.file.Files.createTempDirectory(Files.java:991)
	at randoop.output.FailingTestFilter.createWorkingDirectory(FailingTestFilter.java:483)
	at randoop.output.FailingTestFilter.writeClassCode(FailingTestFilter.java:91)
	at randoop.main.GenTests.writeTestFiles(GenTests.java:597)
	at randoop.main.GenTests.handle(GenTests.java:508)
	at randoop.main.Main.nonStaticMain(Main.java:66)
	at randoop.main.Main.main(Main.java:30)
```

I got a different stack trace, but still on line 991 of `java.nio.file.Files.createTempDirectory`, and still initializing a class within `sun.security....`:

```
Throwable thrown while handling command: java.lang.NoClassDefFoundError: Could not initialize class sun.security.provider.SunEntries
java.lang.NoClassDefFoundError: Could not initialize class sun.security.provider.SunEntries
	at sun.security.provider.Sun.<init>(Sun.java:56)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:221)
	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:206)
	at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:187)
	at sun.security.jca.ProviderList.getProvider(ProviderList.java:233)
	at sun.security.jca.ProviderList$3.get(ProviderList.java:148)
	at sun.security.jca.ProviderList$3.get(ProviderList.java:143)
	at java.util.AbstractList$Itr.next(AbstractList.java:358)
	at java.security.SecureRandom.getPrngAlgorithm(SecureRandom.java:558)
	at java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:194)
	at java.security.SecureRandom.<init>(SecureRandom.java:162)
	at java.nio.file.TempFileHelper.<clinit>(TempFileHelper.java:56)
	at java.nio.file.Files.createTempDirectory(Files.java:991)
	at randoop.output.FailingTestFilter.createWorkingDirectory(FailingTestFilter.java:483)
	at randoop.output.FailingTestFilter.writeClassCode(FailingTestFilter.java:91)
	at randoop.main.GenTests.writeTestFiles(GenTests.java:597)
	at randoop.main.GenTests.handle(GenTests.java:508)
	at randoop.main.Main.nonStaticMain(Main.java:67)
	at randoop.main.Main.main(Main.java:31)
```

In either case, this error within the JDK is suggestive of a classpath problem, or a problem with bytecode instrumentation.  Do you have any ideas along those lines?

**Comment by markro49** [comment]
With master as of this morning I get same as my original report; however, the last sequence under execution is different.

Throwable thrown while handling command: java.lang.NoClassDefFoundError: Could not initialize class sun.security.jca.Providers
java.lang.NoClassDefFoundError: Could not initialize class sun.security.jca.Providers
        at java.security.SecureRandom.getPrngAlgorithm(SecureRandom.java:558)
        at java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:194)
        at java.security.SecureRandom.<init>(SecureRandom.java:162)
        at java.nio.file.TempFileHelper.<clinit>(TempFileHelper.java:56)
        at java.nio.file.Files.createTempDirectory(Files.java:991)
        at randoop.output.FailingTestFilter.createWorkingDirectory(FailingTestFilter.java:492)
        at randoop.output.FailingTestFilter.writeClassCode(FailingTestFilter.java:91)
        at randoop.main.GenTests.writeTestFiles(GenTests.java:592)
        at randoop.main.GenTests.handle(GenTests.java:503)
        at randoop.main.Main.nonStaticMain(Main.java:67)
        at randoop.main.Main.main(Main.java:31)

Randoop failed.
Last sequence under execution:
org.jcodec.codecs.mpeg12.bitstream.SequenceScalableExtension sequenceScalableExtension1 = null;
org.jcodec.common.io.VLC vLC2 = org.jcodec.codecs.mpeg12.bitstream.SequenceScalableExtension.vlcMBType(217, sequenceScalableExtension1);
org.jcodec.codecs.mpeg12.MPEGConst.vlcMBTypeISpat = vLC2;

**Comment by markro49** [comment]
Perhaps the difference is due to different versions of the JDK.   I'm still using an older version 1.8.0_92.

As to the root cause, I am still looking at the test.

**Comment by markro49** [comment]
With the current master version of randoop this problem is nondeterministic.  Fails about 20% of time for me.  Did expose a problem with do-like-javac tools that I have submitted a pull request to fix.
