### ISSUE TITLE
ClassFileConstants - Unrecognized constant of type class randoop.org.apache.bcel.classfile.ConstantInvokeDynamic

### ISSUE THREAD

**Issue by huangwaylon** [randoop/randoop#374]
Randoop version 4.0.4, branch master

I am running Randoop with Randoop's version of constant mining (not GRT's) enabled on the FreeCol project in Toradocu.

To enable Randoop's constant mining, I edited the build.gradle file located at `toradocu-coverage/toradocu/freecol/build.gradle`

The change that I made was to add the two lines:
```
"--literals-file=CLASSES",
"--literals-level=ALL",
```
that adds these two options to the options array on line 146.

Here is the .txt file with the build.gradle contents for FreeCol.
[build.gradle.txt](https://github.com/randoop/randoop/files/2065242/build.gradle.txt)

Within the directory `toradocu-coverage/toradocu/freecol` where toradocu-coverage is the root directory from the repository located at https://gitlab.cs.washington.edu/randoop/toradocu-coverage/tree/master I ran the command:

`./gradlew prepareForCoverage`

The error that I am getting is an unrecognized constant of type class randoop.org.apache.bcel.classfile.ConstantInvokeDynamic.

On line 172 of ClassFileConstants, Randoop doesn't seem to be handling this other type of constant.
I am not sure what the correct thing to do in regards to handling this type - whether to ignore it like some of the other types listed in the ClassFileConstants class above, or to do some additional handling.

```
./gradlew prepareForCoverage

expanded task list: [cleanRandoop, cleanTest, runRandoop, compileTestJava]


expanded task list: [cleanRandoop, cleanTest, runRandoop, compileTestJava]


expanded task list: [cleanRandoop, cleanTest, runRandoop, compileTestJava]


expanded task list: [cleanRandoop, cleanTest, runRandoop, compileTestJava]


expanded task list: [cleanRandoop, cleanTest, runRandoop, compileTestJava]

:freecol:cleanRandoop UP-TO-DATE
:freecol:cleanTest UP-TO-DATE
:freecol:getInputs
WARNING: not cloning repo because already exists.
         Force clone by running with cleanInputs
:freecol:compileInputs UP-TO-DATE
:freecol:makeResourceDir
:freecol:getClassList
:freecol:runRandoop
[java, -ea, -cp, /home/waylonh/toradocu-coverage/toradocu/freecol/inputs/FreeCol/FreeCol.jar:/home/waylonh/toradocu-coverage/toradocu/libs/randoop.jar:/home/waylonh/toradocu-coverage/toradocu/libs/replacecall.jar:/home/waylonh/toradocu-coverage/toradocu/libs/jacocoagent.jar, randoop.main.Main, gentests, --classlist=/home/waylonh/toradocu-coverage/toradocu/freecol/resources/classlist.txt, --time-limit=900, --stop-on-error-test=false, --junit-output-dir=/home/waylonh/toradocu-coverage/toradocu/freecol/src/test/java, --flaky-test-behavior=output, --no-error-revealing-tests, --junit-reflection-allowed=false, --usethreads, --literals-file=CLASSES, --literals-level=ALL, --omitmethods=java\.awt\.Component\.(isMaximumSizeSet|isCursorSet)|net\.sf\.freecol\.(client\.gui\.ImageLibrary(\((float)?\)|\.(getMiscImage|createOverlayCache))|FreeCol\.fatal|common\.(io\.FreeColDirectories\.(getLogWriter|getLogFileContents|getDebugRunSaveFile)|i18n\.Messages\.getUnitLabel|model\.(AbstractGoods\(\)|HighScore\.saveHighScores|Specification\.getFoundingFather|IndianNationType\.getSettlementTypeKey|Turn\.getLabel)|networking\.DOMMessage\.getBooleanAttribute)|server\.FreeColServer\.getGame\(\)), --output-limit=2000]
Ignoring abstract class net.sf.freecol.server.ai.MissionAIPlayer specified via --classlist or --testclass.
Ignoring abstract class net.sf.freecol.server.ai.TransportableAIObject specified via --classlist or --testclass.

Throwable thrown while handling command: java.lang.RuntimeException: Unrecognized constant of type class randoop.org.apache.bcel.classfile.ConstantInvokeDynamic: CONSTANT_InvokeDynamic[18](bootstrap_method_attr_index = 0, name_and_type_index = 518)
java.lang.RuntimeException: Unrecognized constant of type class randoop.org.apache.bcel.classfile.ConstantInvokeDynamic: CONSTANT_InvokeDynamic[18](bootstrap_method_attr_index = 0, name_and_type_index = 518)
        at randoop.util.ClassFileConstants.getConstants(ClassFileConstants.java:172)
        at randoop.util.ClassFileConstants.getConstants(ClassFileConstants.java:122)
        at randoop.reflection.ClassLiteralExtractor.visitBefore(ClassLiteralExtractor.java:30)
        at randoop.reflection.ReflectionManager.visitBefore(ReflectionManager.java:303)
        at randoop.reflection.ReflectionManager.apply(ReflectionManager.java:100)
        at randoop.reflection.ReflectionManager.apply(ReflectionManager.java:83)
        at randoop.reflection.OperationModel.addClassTypes(OperationModel.java:493)
        at randoop.reflection.OperationModel.createModel(OperationModel.java:153)
        at randoop.main.GenTests.handle(GenTests.java:274)
        at randoop.main.Main.nonStaticMain(Main.java:66)
        at randoop.main.Main.main(Main.java:30)

Randoop failed.
Last sequence under execution: 
Exception in thread "main" java.lang.NullPointerException
        at randoop.main.Main.nonStaticMain(Main.java:115)
        at randoop.main.Main.main(Main.java:30)
:freecol:runRandoop FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/waylonh/toradocu-coverage/toradocu/freecol/build.gradle' line: 181

* What went wrong:
Execution failed for task ':freecol:runRandoop'.
> Process 'command 'java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.107 secs

```

**Comment by markro49** [comment]
passed Travis
