### ISSUE TITLE
Throwable thrown while handling command: java.lang.NoClassDefFoundError: randoop/MethodReplacements

### ISSUE THREAD

**Issue by AaratiT** [randoop/randoop#400]
using java 8, randoop-4.0.4 on windows.

command used
 java -ea -cp ".\randoop-4.0.4.jar;.\options-0.3.3.jar;.\javaparser-core-2.0.0.jar;.\classes;commons-exec-1.3.jar;" randoop.main.Main gentests --testclass=c.u.g.KeyClient --junit-output-dir=src/test/java

Output:
  Throwable thrown while handling command: java.lang.NoClassDefFoundError: randoop/MethodReplacements
java.lang.NoClassDefFoundError: randoop/MethodReplacements
        at randoop.main.GenTests.handle(GenTests.java:239)
        at randoop.main.Main.nonStaticMain(Main.java:66)
        at randoop.main.Main.main(Main.java:30)
Caused by: java.lang.ClassNotFoundException: randoop.MethodReplacements
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 more

Randoop failed.
Last sequence under execution:
Exception in thread "main" java.lang.NullPointerException
        at randoop.main.Main.nonStaticMain(Main.java:115)
        at randoop.main.Main.main(Main.java:30)

Appreciate help / suggestions

**Comment by AaratiT** [comment]
In case someone faces similar issue, the problem was I was using wrong randdop jar
The correct jar is 

> randoop-all-4.0.4.jar

And command is 

> java -ea -cp ".\randoop-all-4.0.4.jar;.\options-0.3.3.jar;.\gson-2.2.4.jar;.\javaparser-core-2.0.0.jar;.\target\classes;commons-exec-1.3.jar;" randoop.main.Main gentests --testclass=c.u.g.KeyClient --junit-output-dir=src/test/java
