### ISSUE TITLE
NPE in Bloodhound.incrementSuccessfulInvocationCount when using --method-selection=BLOODHOUND

### ISSUE THREAD

**Issue by gryan-sovrn** [randoop/randoop#414]
Using Randoop 4.1.0 release on Mac OSX.

When running `java -Xmx3000m -classpath .:./target/classes:$RANDOOP_JAR -Xbootclasspath/a:./jacocoagent.jar -javaagent:jacocoagent.jar  randoop.main.Main gentests --classlist=classlistTest.txt --output-limit=5 --method-selection=BLOODHOUND`

I am getting the following exception: 
`Explorer = randoop.generation.ForwardGenerator(allSequences.size()=0,observers.size()=0,subsumed_sequences.size()=0,runtimePrimitivesSeen.size()=38)
Progress update: steps=1, test inputs generated=0, failing inputs=0      (Wed Jan 02 09:17:07 MST 2019)
Throwable thrown while handling command: java.lang.NullPointerException
java.lang.NullPointerException
	at randoop.generation.Bloodhound.incrementSuccessfulInvocationCount(Bloodhound.java:364)
	at randoop.generation.Bloodhound.newRegressionTestHook(Bloodhound.java:385)
	at randoop.generation.ForwardGenerator.newRegressionTestHook(ForwardGenerator.java:138)
	at randoop.generation.AbstractGenerator.createAndClassifySequences(AbstractGenerator.java:335)
	at randoop.main.GenTests.handle(GenTests.java:456)
	at randoop.main.Main.nonStaticMain(Main.java:67)
	at randoop.main.Main.main(Main.java:31)
Randoop failed.`

This can be fixed by autoboxing the output of line 357 of Bloodhound.java.  Change
`int numSuccessfulInvocations = CollectionsPlume.incrementMap(methodInvocationCounts, operation);`
to
`Integer numSuccessfulInvocations = CollectionsPlume.incrementMap(methodInvocationCounts, operation);
 if ( numSuccessfulInvocations == null ) {
          numSuccessfulInvocations = 1;
      }`

**Comment by mernst** [comment]
Thanks for the report and the fix!  I changed this in a slightly different way, by using the new rather than the old value as an argument to `max`.
