### ISSUE TITLE
Some of Randoop's assertion fail due to deprecated methods

### ISSUE THREAD

**Issue by rjust** [randoop/randoop#71]
Randoop creates assertions for floating-point numbers, using `assertEquals` without a delta. These assertions always fail because of the deprecated `assertEquals(double expected, double actual)` method.

Consider the following example:
```
@Test
  public void test160() throws Throwable {
    if (debug) { System.out.format("%n%s%n","RandoopTest0.test160"); }
    double d1 = org.apache.commons.math3.util.FastMath.atan(Double.NaN);
    // Regression assertion (captures the current behavior of the code)
    org.junit.Assert.assertEquals(d1, Double.NaN);
  }
```

The execution of this test results in:
```
junit.framework.AssertionFailedError: Use assertEquals(expected, actual, delta) to compare floating-point numbers
    at org.junit.Assert.fail(Assert.java:88)                                     
    at org.junit.Assert.assertEquals(Assert.java:576)                            
    at org.junit.Assert.assertEquals(Assert.java:565)                            
    at RandoopTest0.test160(RandoopTest0.java:3255)
```

**Comment by bjkeller** [comment]
Thanks René.  This was recently fixed.
