### ISSUE TITLE
randoop.types.WildcardType.forType throw java.lang.StackOverflowError

### ISSUE THREAD

**Issue by yansendao** [randoop/randoop#714]
Thanks for submitting an issue.

Please first search the manual, especially the Troubleshooting section (https://randoop.github.io/randoop/manual/#troubleshooting).  It may already answer your question.

As explained in the instructions for submitting an issue (https://randoop.github.io/randoop/manual/#bug-reporting), include at least the following information.

The version of Randoop, the output of `java -version`, and the operating system version.

```
$ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+0-Cloud-Compiler-JDK-V100R002C00B012)
OpenJDK 64-Bit Server VM (build 11.0.6+0-Cloud-Compiler-JDK-V100R002C00B012, mixed mode)
```

randoop version:
4.2.1

The complete commands you ran, so that we can paste them into a command terminal.  Please don't omit any steps, including installing software or setting environment varibales.

```
1、build openjdk11（get source from adoptopenjdk）：
sudo apt-get -y install autoconf libx11-dev libxext-dev libxrender-dev libxrandr-dev libxtst-dev libxt-dev libcups2-dev libfontconfig1-dev libasound2-dev
bash configure --prefix=$PWD/install --disable-warnings-as-errors --with-debug-level=release --with-version-pre=""
make all

#/home/yansendao/opensource/jdk/jdk11u-dev is the openjdk source root directory

2、generate testcase：
export CLASSPATH=.:$PWD/covered-class.jar:$PWD/randoop-all.jar:$PWD/replacecall.jar:/home/yansendao/opensource/jdk/jdk11u-dev/build/linux-x86_64-normal-server-release/jdk/modules/jdk.internal.vm.compiler
java randoop.main.Main gentests --testclass=org.graalvm.compiler.phases.common.LoweringPhase --time-limit=100 --maxsize=10000
```

A transcript of all the output (as text, not a screenshot).

```
Throwable thrown while handling command: java.lang.StackOverflowError
java.lang.StackOverflowError
	at randoop.types.WildcardType.forType(WildcardType.java:51)
	at randoop.types.WildcardArgument.forType(WildcardArgument.java:38)
	at randoop.types.TypeArgument.forType(TypeArgument.java:31)
	at randoop.types.ParameterizedType.forType(ParameterizedType.java:51)
	at randoop.types.ParameterBound.forType(ParameterBound.java:90)
	at randoop.types.ParameterBound.forTypes(ParameterBound.java:67)
	at randoop.types.TypeVariable.forType(TypeVariable.java:45)
	at randoop.types.GenericClassType.<init>(GenericClassType.java:30)
	at randoop.types.ParameterizedType.forClass(ParameterizedType.java:29)
	at randoop.types.ParameterizedType.forType(ParameterizedType.java:58)
	at randoop.types.ParameterBound.forType(ParameterBound.java:90)
	at randoop.types.ParameterBound.forTypes(ParameterBound.java:67)
	at randoop.types.TypeVariable.forType(TypeVariable.java:45)
```

[randoop.log](https://github.com/randoop/randoop/files/4275455/randoop.log)

What you expected to happen instead.

generate testcase normally.

Files that are used by the commands you ran.

**Comment by mernst** [comment]
Thanks for the bug report; I appreciate it.

You have identified a case where Randoop does a poor job with generics.

For my own reference, the command I ran to reproduce this problem was
```java -classpath $HOME/java/jdk-openjdk11/build/linux-x86_64-normal-server-release/jdk/modules/jdk.internal.vm.compiler:$randoop/build/libs/randoop-all-4.2.2.jar randoop.main.Main gentests --testclass=org.graalvm.compiler.phases.common.LoweringPhase --time-limit=100 --maxsize=10000```
