### ISSUE TITLE
MethodReflectionCode.java:80 error invoking public static java.lang.String java.util.regex.Pattern.quote(java.lang.String) on 1 arguments

### ISSUE THREAD

**Issue by yansendao** [randoop/randoop#715]
Thanks for submitting an issue.

Please first search the manual, especially the Troubleshooting section (https://randoop.github.io/randoop/manual/#troubleshooting).  It may already answer your question.

As explained in the instructions for submitting an issue (https://randoop.github.io/randoop/manual/#bug-reporting), include at least the following information.

The version of Randoop, the output of `java -version`, and the operating system version.

```
$ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+0-Cloud-Compiler-JDK-V100R002C00B012)
OpenJDK 64-Bit Server VM (build 11.0.6+0-Cloud-Compiler-JDK-V100R002C00B012, mixed mode)
```

randoop version:
4.2.1

os version:
Ubuntu 16.04 LTS

The complete commands you ran, so that we can paste them into a command terminal.  Please don't omit any steps, including installing software or setting environment varibales.

```
export CLASSPATH=.:$PWD/covered-class.jar:$PWD/randoop-all.jar:$PWD/replacecall.jar
java -ea randoop.main.Main gentests --testclass=com.sun.tools.javac.util.MatchingUtils --time-limit=100 --maxsize=10000
```

A transcript of all the output (as text, not a screenshot).

```
Progress update: steps=1, test inputs generated=0, failing inputs=0      (Mon Mar 02 18:22:16 CST 2020     70MB used)createAndClassifySequences throw an exception
randoop.util.ReflectionCode$ReflectionCodeException: error invoking public static java.lang.String java.util.regex.Pattern.quote(java.lang.String) on 1 arguments:
  hi!
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:80)
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:59)
	at randoop.util.ReflectionExecutor.executeReflectionCodeUnThreaded(ReflectionExecutor.java:162)
	at randoop.util.ReflectionExecutor.executeReflectionCode(ReflectionExecutor.java:93)
	at randoop.operation.MethodCall.execute(MethodCall.java:180)
	at randoop.operation.TypedOperation.execute(TypedOperation.java:273)
	at randoop.test.RegressionCaptureGenerator.generateTestChecks(RegressionCaptureGenerator.java:209)
	at randoop.test.RegressionCaptureGenerator.generateTestChecks(RegressionCaptureGenerator.java:42)
	at randoop.test.ExtendGenerator.generateTestChecks(ExtendGenerator.java:41)
	at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:340)
	at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:234)
	at randoop.generation.ForwardGenerator.step(ForwardGenerator.java:208)
	at randoop.generation.AbstractGenerator.createAndClassifySequences(AbstractGenerator.java:312)
	at randoop.main.GenTests.handle(GenTests.java:467)
	at randoop.main.Main.nonStaticMain(Main.java:66)
	at randoop.main.Main.main(Main.java:30)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53)
	... 15 more
```

[randoop.log](https://github.com/randoop/randoop/files/4275568/randoop.log)

What you expected to happen instead.

generate testcase normally.

Files that are used by the commands you ran.

**Comment by mernst** [comment]
When I run your command, I get
```
Unable to load class "com.sun.tools.javac.util.MatchingUtils" due to exception: java.lang.ClassNotFoundException: com.sun.tools.javac.util.MatchingUtilsWill explore 0 out of 1 classes
```
You have `.` on the classpath but did not indicate what directory you ran Randoop from.  Can you please give a command that does not put `.` on the classpath?

Also, your classpath is unusual.  Why did you put covered-class.jar and replacecall.jar on the classpath?  That's not how the Randoop manual instructs you to run Randoop.

**Comment by yansendao** [comment]
> When I run your command, I get
> 
> ```
> Unable to load class "com.sun.tools.javac.util.MatchingUtils" due to exception: java.lang.ClassNotFoundException: com.sun.tools.javac.util.MatchingUtilsWill explore 0 out of 1 classes
> ```
> 
> You have `.` on the classpath but did not indicate what directory you ran Randoop from. Can you please give a command that does not put `.` on the classpath?
> 
> Also, your classpath is unusual. Why did you put covered-class.jar and replacecall.jar on the classpath? That's not how the Randoop manual instructs you to run Randoop.

I think the randoop 4.2.2 has fixed this problem.


java -ea -cp randoop-all-4.2.1.jar randoop.main.Main gentests --testclass=com.sun.tools.javac.util.MatchingUtils --time-limit=10 --maxsize=100 &> randoop-4.2.1.log ; echo $?

![image](https://user-images.githubusercontent.com/36258307/75741199-d3281480-5d44-11ea-84e6-b83fce8e9a57.png)





java -ea -cp randoop-all-4.2.2.jar randoop.main.Main gentests --testclass=com.sun.tools.javac.util.MatchingUtils --time-limit=10 --maxsize=100 &> randoop-4.2.2.log ; echo $?





![image](https://user-images.githubusercontent.com/36258307/75741212-e3d88a80-5d44-11ea-9f33-46b1adabce89.png)

**Comment by mernst** [comment]
Thank you for confirming that the newer release fixes the problem.
