### ISSUE TITLE
genterate testcase for sun.security.util.BitArray cause java.lang.ArrayIndexOutOfBoundsException: -8

### ISSUE THREAD

**Issue by yansendao** [randoop/randoop#717]
Thanks for submitting an issue.

Please first search the manual, especially the Troubleshooting section (https://randoop.github.io/randoop/manual/#troubleshooting).  It may already answer your question.

As explained in the instructions for submitting an issue (https://randoop.github.io/randoop/manual/#bug-reporting), include at least the following information.

The version of Randoop, the output of `java -version`, and the operating system version.

```
$ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+0-Cloud-Compiler-JDK-V100R002C00B012)
OpenJDK 64-Bit Server VM (build 11.0.6+0-Cloud-Compiler-JDK-V100R002C00B012, mixed mode)
```

randoop version:
4.2.1

os version:
Ubuntu 16.04 LTS

The complete commands you ran, so that we can paste them into a command terminal.  Please don't omit any steps, including installing software or setting environment varibales.

```
export CLASSPATH=.:$PWD/covered-class.jar:$PWD/randoop-all.jar:$PWD/replacecall.jar
java -ea randoop.main.Main gentests --testclass=sun.security.util.BitArray --time-limit=100 --maxsize=10000
```

A transcript of all the output (as text, not a screenshot).

```
java.lang.ArrayIndexOutOfBoundsException: -8
	at java.base/sun.security.util.BitArray.get(BitArray.java:129)
	at java.base/sun.security.util.BitArray.toString(BitArray.java:259)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
	at randoop.test.RegressionCaptureGenerator.generateTestChecks(RegressionCaptureGenerator.java:217)
	at randoop.test.RegressionCaptureGenerator.generateTestChecks(RegressionCaptureGenerator.java:42)
	at randoop.test.ExtendGenerator.generateTestChecks(ExtendGenerator.java:41)
	at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:340)
	at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:234)
	at randoop.generation.ForwardGenerator.step(ForwardGenerator.java:208)
	at randoop.generation.AbstractGenerator.createAndClassifySequences(AbstractGenerator.java:312)
	at randoop.main.GenTests.handle(GenTests.java:467)
	at randoop.main.Main.nonStaticMain(Main.java:66)
	at randoop.main.Main.main(Main.java:30)
```

[randoop.log](https://github.com/randoop/randoop/files/4275658/randoop.log)

What you expected to happen instead.

generate testcase normally.

Files that are used by the commands you ran.

**Comment by mernst** [comment]
I was not able to reproduce this crash using the latest released version of Randoop.  Could you please try with Randoop 4.2.2?

**Comment by yansendao** [comment]
> I was not able to reproduce this crash using the latest released version of Randoop. Could you please try with Randoop 4.2.2?

I think the randoop 4.2.2 has fix this problem.

![image](https://user-images.githubusercontent.com/36258307/75747971-4c316700-5d59-11ea-948f-713a44d091d5.png)



[randoop-4.2.1.log](https://github.com/randoop/randoop/files/4279559/randoop-4.2.1.log)
[randoop-4.2.2.log](https://github.com/randoop/randoop/files/4279560/randoop-4.2.2.log)
