### ISSUE TITLE
generate testcase for java.util.concurrent.Semaphore cause randoop BLOCKED

### ISSUE THREAD

**Issue by yansendao** [randoop/randoop#718]
Thanks for submitting an issue.

Please first search the manual, especially the Troubleshooting section (https://randoop.github.io/randoop/manual/#troubleshooting).  It may already answer your question.

As explained in the instructions for submitting an issue (https://randoop.github.io/randoop/manual/#bug-reporting), include at least the following information.

The version of Randoop, the output of `java -version`, and the operating system version.

```
$ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+0-Cloud-Compiler-JDK-V100R002C00B012)
OpenJDK 64-Bit Server VM (build 11.0.6+0-Cloud-Compiler-JDK-V100R002C00B012, mixed mode)
```

randoop version:
4.2.1

os version:
Ubuntu 16.04 LTS

The complete commands you ran, so that we can paste them into a command terminal.  Please don't omit any steps, including installing software or setting environment varibales.

```
1. start randoop, and wait for 10 minutes

export CLASSPATH=.:$PWD/covered-class.jar:$PWD/randoop-all.jar:$PWD/replacecall.jar
java -ea randoop.main.Main gentests --testclass=java.util.concurrent.Semaphore --time-limit=100 --maxsize=10000

2. start a new bash client, and get the jstack result for randoop:
$ ps -ef | grep java.util.concurrent.Semaphore
$ jstack 31355 > stack-randoop.log  #31355 is the randoop pid

```

A transcript of all the output (as text, not a screenshot).

```
"main" #1 prio=5 os_prio=0 cpu=4578.16ms elapsed=1673.11s tid=0x00007fb698014000 nid=0x7a81 waiting on condition  [0x00007fb6a0c9f000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.6/Native Method)
        - parking to wait for  <0x00000000ff153250> (a java.util.concurrent.Semaphore$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.6/LockSupport.java:194)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.6/AbstractQueuedSynchronizer.java:885)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(java.base@11.0.6/AbstractQueuedSynchronizer.java:1039)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@11.0.6/AbstractQueuedSynchronizer.java:1345)
        at java.util.concurrent.Semaphore.acquire(java.base@11.0.6/Semaphore.java:475)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.6/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.6/NativeMethodAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.6/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@11.0.6/Method.java:566)
        at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53)
        at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:59)
        at randoop.util.ReflectionExecutor.executeReflectionCodeUnThreaded(ReflectionExecutor.java:162)
        at randoop.util.ReflectionExecutor.executeReflectionCode(ReflectionExecutor.java:93)
        at randoop.operation.MethodCall.execute(MethodCall.java:180)
        at randoop.operation.TypedOperation.execute(TypedOperation.java:273)
        at randoop.sequence.Statement.execute(Statement.java:163)
        at randoop.sequence.ExecutableSequence.executeStatement(ExecutableSequence.java:409)
        - locked <0x00000000824bacd8> (a java.lang.Object)
        at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:306)
        at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:234)
        at randoop.generation.ForwardGenerator.step(ForwardGenerator.java:208)
        at randoop.generation.AbstractGenerator.createAndClassifySequences(AbstractGenerator.java:312)
        at randoop.main.GenTests.handle(GenTests.java:467)
        at randoop.main.Main.nonStaticMain(Main.java:66)
        at randoop.main.Main.main(Main.java:30)


"randoop.util.ProgressDisplay" #26 daemon prio=5 os_prio=0 cpu=87.69ms elapsed=1669.88s tid=0x00007fb698a3f000 nid=0x7fcd waiting for monitor entry  [0x00007fb5ebcfd000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at randoop.util.ProgressDisplay.display(ProgressDisplay.java:220)
        - waiting to lock <0x00000000824bacd8> (a java.lang.Object)
        at randoop.util.ProgressDisplay.display(ProgressDisplay.java:209)
        at randoop.util.ProgressDisplay.run(ProgressDisplay.java:88)
```

[stack-randoop.log](https://github.com/randoop/randoop/files/4275721/stack-randoop.log)

What you expected to happen instead.

generate testcase normally.

Files that are used by the commands you ran.

**Comment by mernst** [comment]
Can you provide an example of a test that you would like Randoop to generate?

**Comment by yansendao** [comment]
> Can you provide an example of a test that you would like Randoop to generate?

I want to generate unit tests for java11 API of java.util.concurrent.Semaphore.

**Comment by mernst** [comment]
I will repeat my question:
Can you provide an example of a test that you would like Randoop to generate?

An example is a concrete, runnable JUnit test case.

**Comment by yansendao** [comment]
> I will repeat my question:
> Can you provide an example of a test that you would like Randoop to generate?
> 
> An example is a concrete, runnable JUnit test case.

The JDK11 API java.util.concurrent.Semaphore is the testcase what I want to test.

**Comment by mernst** [comment]
I'm closing this issue because we seem to be talking at cross purposes.
If you can provide a `.java` file that I can compile and run (that tests `Semaphore`), I am very happy to reopen the issue.
