### ISSUE TITLE
Randoop failed in an unexpected way: RegressionTest0 has been compiled by a more recent version of the Java Runtime

### ISSUE THREAD

**Issue by swanaselja** [randoop/randoop#781]
randoop-4.2.3

java 11.0.1 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)

MacOS 10.15.5

my command:

/Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/bin/java -classpath '/Users/swanaselja/Documents/workspace_econ_Yo/FamilyNetGen/target/classes/':randoop-all-4.2.3.jar randoop.main.Main gentests --testclass=familynetgen.FNetDateTimeLocal --time-limit=60

The resulting output:

```
Randoop for Java version 4.2.3.
Will explore 1 classes
PUBLIC MEMBERS=10
Explorer = ForwardGenerator(steps: 0, null steps: 0, num_sequences_generated: 0;
    allSequences: 0, regresson seqs: 0, error seqs: 0=0=0, invalid seqs: 0, subsumed_sequences: 0, num_failed_output_test: 0;
    runtimePrimitivesSeen:38)

Progress update: steps=1, test inputs generated=0, failing inputs=0      (Sat Jun 06 20:31:19 PDT 2020     6MB used)
Progress update: steps=1000, test inputs generated=2, failing inputs=0      (Sat Jun 06 20:31:20 PDT 2020     34MB used)
Progress update: steps=2000, test inputs generated=2, failing inputs=0      (Sat Jun 06 20:31:20 PDT 2020     38MB used)

...

Progress update: steps=11335000, test inputs generated=2, failing inputs=0      (Sat Jun 06 20:23:40 PDT 2020     73MB used)
Progress update: steps=11336000, test inputs generated=2, failing inputs=0      (Sat Jun 06 20:23:40 PDT 2020     77MB used)
Progress update: steps=11337000, test inputs generated=2, failing inputs=0      (Sat Jun 06 20:23:40 PDT 2020     80MB used)
Progress update: steps=11337293, test inputs generated=2, failing inputs=0      (Sat Jun 06 20:23:40 PDT 2020     81MB used)
Normal method executions: 12
Exceptional method executions: 0

Average method execution time (normal termination):      0.0106
Average method execution time (exceptional termination): NaN
Approximate memory usage 81MB
Explorer = ForwardGenerator(steps: 11337293, null steps: 11337291, num_sequences_generated: 2;
    allSequences: 2, regresson seqs: 1, error seqs: 0=0=0, invalid seqs: 0, subsumed_sequences: 0, num_failed_output_test: 1;
    runtimePrimitivesSeen:38)

No error-revealing tests to output.

About to look for failing assertions in 1 regression sequences.

Regression test output:
Regression test count: 1

Writing regression JUnit tests...
                                                                                                                                     GenTests.writeTestFiles threw an exception                        
randoop.main.RandoopBug: Did not find "There\s+(?:was|were)\s+(\d+)\s+failure(?:s|):" in execution of RegressionTest0
status=Status 1 (timedOut=false) for command "java -ea -Xmx3000m -XX:+HeapDumpOnOutOfMemoryError -classpath .:/Users/swanaselja/Documents/workspace_econ_Yo/FamilyNetGen/target/classes:/Users/swanaselja/Documents/workspace_econ_Yo/randoop-4.2.3/randoop-all-4.2.3.jar org.junit.runner.JUnitCore RegressionTest0", stdout="JUnit version 4.13"
, stderr lines=22
Standard output:
JUnit version 4.13
... end of standard output.Error output:
Exception in thread "main" java.lang.UnsupportedClassVersionError: RegressionTest0 has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.junit.internal.Classes.getClass(Classes.java:42)
	at org.junit.internal.Classes.getClass(Classes.java:27)
	at org.junit.runner.JUnitCommandLineParseResult.parseParameters(JUnitCommandLineParseResult.java:98)
	at org.junit.runner.JUnitCommandLineParseResult.parseArgs(JUnitCommandLineParseResult.java:50)
	at org.junit.runner.JUnitCommandLineParseResult.parse(JUnitCommandLineParseResult.java:44)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:72)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
... end of error output.

	at randoop.output.FailingAssertionCommentWriter.numJunitFailures(FailingAssertionCommentWriter.java:442)
	at randoop.output.FailingAssertionCommentWriter.commentFailingAssertions(FailingAssertionCommentWriter.java:292)
	at randoop.output.FailingAssertionCommentWriter.writeClassCode(FailingAssertionCommentWriter.java:172)
	at randoop.main.GenTests.writeTestFiles(GenTests.java:858)
	at randoop.main.GenTests.handle(GenTests.java:559)
	at randoop.main.Main.nonStaticMain(Main.java:70)
	at randoop.main.Main.main(Main.java:30)
Caused by: randoop.output.FailingAssertionCommentWriter$NotMatchedException
	at randoop.output.FailingAssertionCommentWriter.readUntilMatch(FailingAssertionCommentWriter.java:511)
	at randoop.output.FailingAssertionCommentWriter.numJunitFailures(FailingAssertionCommentWriter.java:398)
	... 6 more

Randoop failed in an unexpected way.
Please report at https://github.com/randoop/randoop/issues ,
providing the information requested at https://randoop.github.io/randoop/manual/index.html#bug-reporting .
randoop.main.RandoopBug: Did not find "There\s+(?:was|were)\s+(\d+)\s+failure(?:s|):" in execution of RegressionTest0
status=Status 1 (timedOut=false) for command "java -ea -Xmx3000m -XX:+HeapDumpOnOutOfMemoryError -classpath .:/Users/swanaselja/Documents/workspace_econ_Yo/FamilyNetGen/target/classes:/Users/swanaselja/Documents/workspace_econ_Yo/randoop-4.2.3/randoop-all-4.2.3.jar org.junit.runner.JUnitCore RegressionTest0", stdout="JUnit version 4.13"
, stderr lines=22
Standard output:
JUnit version 4.13
... end of standard output.Error output:
Exception in thread "main" java.lang.UnsupportedClassVersionError: RegressionTest0 has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.junit.internal.Classes.getClass(Classes.java:42)
	at org.junit.internal.Classes.getClass(Classes.java:27)
	at org.junit.runner.JUnitCommandLineParseResult.parseParameters(JUnitCommandLineParseResult.java:98)
	at org.junit.runner.JUnitCommandLineParseResult.parseArgs(JUnitCommandLineParseResult.java:50)
	at org.junit.runner.JUnitCommandLineParseResult.parse(JUnitCommandLineParseResult.java:44)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:72)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
... end of error output.

	at randoop.output.FailingAssertionCommentWriter.numJunitFailures(FailingAssertionCommentWriter.java:442)
	at randoop.output.FailingAssertionCommentWriter.commentFailingAssertions(FailingAssertionCommentWriter.java:292)
	at randoop.output.FailingAssertionCommentWriter.writeClassCode(FailingAssertionCommentWriter.java:172)
	at randoop.main.GenTests.writeTestFiles(GenTests.java:858)
	at randoop.main.GenTests.handle(GenTests.java:559)
	at randoop.main.Main.nonStaticMain(Main.java:70)
	at randoop.main.Main.main(Main.java:30)
Caused by: randoop.output.FailingAssertionCommentWriter$NotMatchedException
	at randoop.output.FailingAssertionCommentWriter.readUntilMatch(FailingAssertionCommentWriter.java:511)
	at randoop.output.FailingAssertionCommentWriter.numJunitFailures(FailingAssertionCommentWriter.java:398)
	... 6 more
```

Let me know if you need the java or class that I was trying to test. But it doesn't seem relevant for this failure.

**Comment by mernst** [comment]
Method `compileTestClass` used a Java 11 `javac` compiler, but method `runTest` used a Java 8 `java` JVM.

 * `compileTestClass` calls `Filecompiler.compile` which gets the compiler from `javax.tools.ToolProvider.getSystemJavaCompiler()`.
 * `runTest` uses whatever `java` is on your path.

These differ, which suggests a misconfiguration, or at least a discrepancy, in your system configuration.

What is the output when you run `java -version` (no absolute path, just as shown) and `javac -version`?

**Comment by swanaselja** [comment]
java -version
openjdk version "1.8.0_172"
OpenJDK Runtime Environment (Zulu 8.30.0.2-macosx) (build 1.8.0_172-b01)
OpenJDK 64-Bit Server VM (Zulu 8.30.0.2-macosx) (build 25.172-b01, mixed mode)
   javac -version
javac 1.8.0_172

This is why I was using the explicit absolute path. Are you saying randoop doesn't necessarily stay with the java I specified on the command line?  I don't recall the user guide saying anything about having to set environment variable(s)...

**Comment by swanaselja** [comment]
I was developing the code-to-be-tested in Eclipse, which has it's own Java environment. Perhaps you can't just point randoop at a class that was generated by Eclipse?

**Comment by mernst** [comment]
Thanks for showing the output of the command.  This shows that your default JDK version is 8, not 11.

Please use the default version of Java when you run Randoop.  That's how all the examples in the manual are shown.

Randoop does not try to guess a non-default version of Java that is installed, based on the path to the Java executable that was used to launch it.  (I don't even know how to do that!  If you want to contribute a patch that does so, I would happily accept it.)

Your use of Eclipse is not relevant.

I hope this helps.
