### ISSUE TITLE
Randoop failed in an unexpected way. GenTests.writeTestFiles threw an exception

### ISSUE THREAD

**Issue by ykj1414** [randoop/randoop#790]
randoop-4.2.4

java1.8.0_201
Java(TM) SE Runtime Environment 18.9 (build 11+28)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)

MacOs 10.14.6

My command:
      **I included randoop-all-4.2.4.jar file in my project and I set vm options and program arguments as below:**
      VM options: -cp .:$RANDOOP_DIR
      Program arguments: gentests --testclass=S_128 --output-limit=60 --junit-output-dir=./randoopTests

The resulting output:

```
GenTests.writeTestFiles threw an exception
randoop.main.RandoopBug: Check configuration of test environment: initialization error of test in flaky-test filter: 1) initializationError(org.junit.runner.JUnitCommandLineParseResult)
	at randoop.output.FailingAssertionCommentWriter.commentFailingAssertions(FailingAssertionCommentWriter.java:314)
	at randoop.output.FailingAssertionCommentWriter.writeClassCode(FailingAssertionCommentWriter.java:172)
	at randoop.main.GenTests.writeTestFiles(GenTests.java:861)
	at randoop.main.GenTests.handle(GenTests.java:562)
	at randoop.main.Main.nonStaticMain(Main.java:89)
	at randoop.main.Main.strategyMain(Main.java:51)
	at Solutions.main(Solutions.java:147)

Randoop failed in an unexpected way.
Please report at https://github.com/randoop/randoop/issues ,
providing the information requested at https://randoop.github.io/randoop/manual/index.html#bug-reporting .
randoop.main.RandoopBug: Check configuration of test environment: initialization error of test in flaky-test filter: 1) initializationError(org.junit.runner.JUnitCommandLineParseResult)
	at randoop.output.FailingAssertionCommentWriter.commentFailingAssertions(FailingAssertionCommentWriter.java:314)
	at randoop.output.FailingAssertionCommentWriter.writeClassCode(FailingAssertionCommentWriter.java:172)
	at randoop.main.GenTests.writeTestFiles(GenTests.java:861)
	at randoop.main.GenTests.handle(GenTests.java:562)
	at randoop.main.Main.nonStaticMain(Main.java:89)
	at randoop.main.Main.strategyMain(Main.java:51)
	at Solutions.main(Solutions.java:147)

```

Let me know if you need the java or class that I was trying to test. But it doesn't seem relevant for this failure because if I switch project sdk to Java11, this problem won't happen.

**Comment by mernst** [comment]
I'm sorry you are having trouble.  We would like to help you, but we cannot do so from this incomplete bug report.  I'm glad you can work around the problem by using JDK 11, but we cannot reproduce or fix the problem from this incomplete bug report.  Can you please provide all the details that were requested in the [issue template](https://github.com/randoop/randoop/issues/new) and the [bug reporting section of the manual](https://randoop.github.io/randoop/manual/#bug-reporting)?  This will enable us to reproduce the problem, fix it, and verify the fix.  Thanks!

**Comment by mernst** [comment]
> Let me know if you need the java or class that I was trying to test.

We asked for this a week ago.  Could you please provide a way to reproduce your problem?

**Comment by ykj1414** [comment]
> > Let me know if you need the java or class that I was trying to test.
> 
> We asked for this a week ago. Could you please provide a way to reproduce your problem?

I'm so sorry for forgetting  to close this problem. Since I used jdk11 this problem has never ocurred again in idea and command-line.And when I tested randoop in command-line by using jdk8 and same command, it succeeded.So I think randoop has nothing to do with my problem. Thank you anyway.
