### ISSUE TITLE
Access control violation for protected/package fields when using --junit-package-name

### ISSUE THREAD

**Issue by jgaleotti** [randoop/randoop#80]
Randoop crashes when using the `--junit-package-name` option and the target class has `protected` or `package` fields.

For example, the following class:
```
package com.example;
public class Foo {
	protected int protectedField;
	int packageField;
}
```
leads to the following stack trace:
```
randoop.BugInRandoopException: Access control violation for field: Class randoop.operation.PublicField can not access a member of class com.example.Foo with modifiers ""
	at randoop.operation.PublicField.setValue(PublicField.java:155)
	at randoop.operation.FieldSetter.execute(FieldSetter.java:88)
	at randoop.sequence.Statement.execute(Statement.java:189)
	at randoop.sequence.ExecutableSequence.executeStatement(ExecutableSequence.java:398)
	at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:312)
	at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:263)
	at randoop.sequence.ForwardGenerator.step(ForwardGenerator.java:129)
	at randoop.sequence.AbstractGenerator.explore(AbstractGenerator.java:299)
Randoop failed.
	at randoop.main.GenTests.handle(GenTests.java:410)
	at randoop.main.Main.nonStaticMain(Main.java:77)
	at randoop.main.Main.main(Main.java:39) 
```
when using the command:
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home//bin/java -cp /Users/galeotti/workspace-sbstcomp/sbstcomp-randoop-4th/target/test-classes:/Users/galeotti/randoop/dist/randoop.jar randoop.main.Main gentests --testclass=com.example.Foo --timelimit=10 --junit-output-dir=/Users/galeotti/temp/testcases --junit-package-name=com.example --clear=10000 --string-maxlen=5000 --forbid-null=false --null-ratio=0.1 --no-error-revealing-tests=true --omitmethods=random 
```

**Comment by bjkeller** [comment]
Thanks. I'm working on it.

**Comment by bjkeller** [comment]
My apologies. An "old" bug from when I added fields with a one line solution.
